pipeline {
    agent any
    environment {
        KUBECONFIG = '/var/lib/jenkins/.kube/config'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/elie1234567/flaskphyton.git', branch: 'main'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r flask_app/requirements.txt'
            }
        }
        stage('Tests') {
            steps {
                sh 'python3 flask_app/test.py'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'eval $(minikube docker-env)'
                sh 'docker build -t flask_hello:latest flask_app/'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f flask_app/kubernetes/deployment.yaml'
                sh 'kubectl apply -f flask_app/kubernetes/service.yml'
            }
        }
    }
}
