pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/elie1234567/flaskphyton.git', branch: 'main'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'pip install -r mini_projet_docker/flask_app/requirements.txt'
            }
        }

        stage('Tests') {
            steps {
                bat '"C:\\Users\\elie donacien\\AppData\\Local\\Programs\\Python\\Python313\\python.exe" flaskphyton\\flask_app\\test.py'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t localhost:4000/flask_hello:latest flaskphyton/flask_app/'
            }
        }

        stage('Push Docker Image') {
            steps {
                bat 'docker push localhost:4000/flask_hello:latest'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                bat 'kubectl apply -f flaskphyton/flask_app/kubernetes/deployement.yml'
                bat 'kubectl apply -f flaskphyton/flask_app/kubernetes/service.yml'
            }
        }
    }
}
